### ISSUE TITLE
OS X Docker container fails to start - fails to find '.http-mitm-proxy/certs/ca.pem' in container

### ISSUE THREAD

**Issue by DoubleDroz** [justinleewells/pogo-optimizer#132]
I'm getting the following error when trying to run the docker instance in 10.11.6:

```
[08:53:25] Finished 'default' after 9.4 μs
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT: no such file or directory, open '.http-mitm-proxy/certs/ca.pem'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.<anonymous> (/code/index.js:20:46)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
npm info lifecycle pogo-optimizer@1.3.0~start: Failed to exec start script
npm ERR! Linux 4.4.15-moby
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! pogo-optimizer@1.3.0 start: `gulp && node index`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pogo-optimizer@1.3.0 start script 'gulp && node index'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pogo-optimizer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp && node index
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pogo-optimizer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pogo-optimizer
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /code/npm-debug.log
```

I thought the docker container had everything it needed to run? Is this an issue with my local environment?

**Comment by deathisabove** [comment]
Same for fresh install on Ubuntu 14.04, non-docker.
Log on pastebin http://pastebin.com/W9j3YNhn

**Comment by Toommmm** [comment]
Same on Fedora 23

**Comment by nubs** [comment]
Duplicate with #133

**Comment by justinleewells** [comment]
Fixed in justinleewells/pogo-optimizer@29dfdd5

**Comment by DoubleDroz** [comment]
Hey @justinleewells I'm still getting exactly the same error

I've pulled, changed branches, and I even downloaded the 1.3.1 tagged release, unzipped and tried again. 

Docker container fails to open.

**Comment by justinleewells** [comment]
Yeah, that must not be the right version. I would delete the directory and re-clone.

**Comment by DoubleDroz** [comment]
Tried re-cloning from master, and also downloading the tagged 1.3.1 release. 

Will try restarting my computer after deleting again...

**Comment by nubs** [comment]
are you rebuilding the docker image?

**Comment by justinleewells** [comment]
You can also use the justinleewells/pogo-optimizer image. It's set to auto-build after each push.

**Comment by DoubleDroz** [comment]
Looks like I'm not sure about how docker works.

I `rmi`'d the existing containers, and then did a `docker build --pull .` in the pogo directory. 

This pulled the new dicker image and - most importantly - built it. 

@justinleewells I thought I *was* using the justinleewells/pogo-optimizer image by running `docker run -d -p 3000:3000 -p 8081:8081 -it justinleewells/pogo-optimizer` after a pull?

**Comment by justinleewells** [comment]
So `docker run -d -p 3000:3000 -p 8081:8081 -it justinleewells/pogo-optimizer` pulls a prebuilt image from dockerhub. You don't even have to mess with using git.

**Comment by DoubleDroz** [comment]
Ok, but that's been the only command I've been using since last night. Perhaps it's an issue with my docker setup?

**Comment by justinleewells** [comment]
Actually, you need to do `docker pull justinleewells/pogo-optimizer` before you do `docker run -d -p 3000:3000 -p 8081:8081 -it justinleewells/pogo-optimizer`. My bad.
