### ISSUE TITLE
Eggs display as 0 km

### ISSUE THREAD

**Issue by andrewda** [justinleewells/pogo-optimizer#9]
The correct number of eggs appear under the egg tab, but they all appear as "0.0 / 0.0 km". Also, incubators do not appear on the eggs that are being incubated.

![img_0381](https://cloud.githubusercontent.com/assets/10191084/16961992/b3bb854a-4da4-11e6-909c-cc98a64bc211.PNG)

**Comment by justinleewells** [comment]
My guess is that protobuf isn't properly decoding the data for eggs, but I'll look into it

**Comment by justinleewells** [comment]
This is fixed in justinleewells/pogo-optimizer@0c7ea60

**Comment by esfomeado** [comment]
@justinleewells I tested this with the last commit from pokemon-go-mitm-node and the problem still happens and the same with move names not appearing.

**Comment by justinleewells** [comment]
Did you `rm -rf node_modules && npm install` or did you just pull it?

**Comment by esfomeado** [comment]
rm -rf node_modules && npm install

I will try to build the latest protobuf files to see if solves anything.

**Comment by esfomeado** [comment]
I can confirm that with the latest protobuf files this problem is solved.
